title: <p align="center"> Ram Thiruvadi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ramagovindaraja-thiruvadi-600110b">LinkedIn</a> |
  <a href="https://github.com/tramgo">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  
  <br>
  </p>



theme: jekyll-theme-minimal
